# ConfigMap containing the HTML template with environment variable
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index-template
  namespace: default
data:
  index.template.html: |
    <html>
    <head><title>Node Info</title></head>
    <body>
      <h1>This pod is running on: $NODE_NAME</h1>
    </body>
    </html>
---
# ConfigMap containing the default nginx configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-default-conf
  namespace: default
data:
  default.conf: |
    server {
        listen 80 default_server;
        listen [::]:80 default_server;

        location / {
            root /usr/share/nginx/html;
            index index.html;
        }

        location = /404.html {
            internal;
        }
    }
---
# DaemonSet to run nginx on each node, using the ConfigMaps. Uses envsubst to get the node name.
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-configmap-on-each-node
  namespace: default
spec:
  selector:
    matchLabels:
      app: nginx-configmap-on-each-node
  template:
    metadata:
      labels:
        app: nginx-configmap-on-each-node
    spec:
      containers:
      - name: nginx
        image: alpine
        ports:
        - containerPort: 80
          hostPort: 82
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: template
          mountPath: /etc/nginx/html
        - name: html
          mountPath: /usr/share/nginx/html
        - name: nginx-conf
          mountPath: /etc/nginx/http.d/default.conf
          subPath: default.conf
        command: ["/bin/sh"]
        args:
        - -c
        - |
          apk add --no-cache nginx gettext curl && \
          envsubst < /etc/nginx/html/index.template.html > /usr/share/nginx/html/index.html && \
          nginx -g 'daemon off;'
      volumes:
      - name: template
        configMap:
          name: nginx-index-template
      - name: html
        emptyDir: {}
      - name: nginx-conf
        configMap:
          name: nginx-default-conf