apiVersion: v1
kind: Service
metadata:
  name: grafana-lb
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: grafana
  ports:
    - port: 3000
      targetPort: 3000
