apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
spec:
  capacity:
    storage: 8Gi   # adjust to match Prometheus PVC request
  accessModes:
    - ReadWriteOnce
  #storageClassName: hostpath
  hostPath:
    path: /data/prometheus   # directory on your node
    type: DirectoryOrCreate
