apiVersion: v1
kind: Service
metadata:
  name: prometheus-lb
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: server
  ports:
    - port: 9090
      targetPort: 9090
